# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jipe}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nat Budin"]
  s.date = %q{2011-03-15}
  s.email = %q{natbudin@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "Gemfile",
    "README",
    "Rakefile",
    "app/controllers/jipe_controller.rb",
    "app/views/jipe/jester.js.erb",
    "app/views/jipe/jipe.js.erb",
    "assets/images/edit-field.png",
    "assets/javascripts/jester.js",
    "assets/javascripts/jipe.js",
    "generators/jipe/USAGE",
    "generators/jipe/jipe_generator.rb",
    "generators/jipe/templates/edit-field.png",
    "init.rb",
    "install.rb",
    "lib/jipe.rb",
    "rails/init.rb",
    "tasks/jipe_tasks.rake",
    "test/jipe_test.rb",
    "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/nbudin/jipe}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{RESTful In-place editors for Rails using Jester}
  s.test_files = [
    "test/jipe_test.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
  end
end

